//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolBX.TimeProvider.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToolBX.TimeProvider.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CannotAddDaysToCurrentDateBecauseValueIsLowerThanZero {
            get {
                return ResourceManager.GetString("CannotAddDaysToCurrentDateBecauseValueIsLowerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CannotAddHoursToCurrentDateBecauseValueIsLowerThanZero {
            get {
                return ResourceManager.GetString("CannotAddHoursToCurrentDateBecauseValueIsLowerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CannotAddMillisecondsToCurrentDateBecauseValueIsLowerThanZero {
            get {
                return ResourceManager.GetString("CannotAddMillisecondsToCurrentDateBecauseValueIsLowerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CannotAddMinutesToCurrentDateBecauseValueIsLowerThanZero {
            get {
                return ResourceManager.GetString("CannotAddMinutesToCurrentDateBecauseValueIsLowerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CannotAddMonthsToCurrentDateBecauseValueIsLowerThanZero {
            get {
                return ResourceManager.GetString("CannotAddMonthsToCurrentDateBecauseValueIsLowerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CannotAddSecondsToCurrentDateBecauseValueIsLowerThanZero {
            get {
                return ResourceManager.GetString("CannotAddSecondsToCurrentDateBecauseValueIsLowerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add years to current date : value must be a positive number greater than zero but it was {0}.
        /// </summary>
        internal static string CannotAddYearsToCurrentDateBecauseValueIsLowerThanZero {
            get {
                return ResourceManager.GetString("CannotAddYearsToCurrentDateBecauseValueIsLowerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CannotSubtractDaysFromCurrentDateBecauseValueIsLowerThanZero {
            get {
                return ResourceManager.GetString("CannotSubtractDaysFromCurrentDateBecauseValueIsLowerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CannotSubtractHoursFromCurrentDateBecauseValueIsLowerThanZero {
            get {
                return ResourceManager.GetString("CannotSubtractHoursFromCurrentDateBecauseValueIsLowerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CannotSubtractMillisecondsFromCurrentDateBecauseValueIsLowerThanZero {
            get {
                return ResourceManager.GetString("CannotSubtractMillisecondsFromCurrentDateBecauseValueIsLowerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CannotSubtractMinutesFromCurrentDateBecauseValueIsLowerThanZero {
            get {
                return ResourceManager.GetString("CannotSubtractMinutesFromCurrentDateBecauseValueIsLowerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CannotSubtractMonthsFromCurrentDateBecauseValueIsLowerThanZero {
            get {
                return ResourceManager.GetString("CannotSubtractMonthsFromCurrentDateBecauseValueIsLowerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CannotSubtractSecondsFromCurrentDateBecauseValueIsLowerThanZero {
            get {
                return ResourceManager.GetString("CannotSubtractSecondsFromCurrentDateBecauseValueIsLowerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t subtract years from current date : value must be a positive number greater than zero but it was {0}.
        /// </summary>
        internal static string CannotSubtractYearsFromCurrentDateBecauseValueIsLowerThanZero {
            get {
                return ResourceManager.GetString("CannotSubtractYearsFromCurrentDateBecauseValueIsLowerThanZero", resourceCulture);
            }
        }
    }
}
